
package br.com.bradesco.filenet.facade;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IntegracaoFileNetCEService", targetNamespace = "http://facade.filenet.bradesco.com.br", wsdlLocation = "file:/C:/Users/LSCT/Desktop/GCC_gccn_integracaofilenet_ce_ws.ear/gccn_integracaofilenet_ce_ws.war/WEB-INF/wsdl/IntegracaoFileNetCE.wsdl")
public class IntegracaoFileNetCEService
    extends Service
{

    private final static URL INTEGRACAOFILENETCESERVICE_WSDL_LOCATION;
    private final static WebServiceException INTEGRACAOFILENETCESERVICE_EXCEPTION;
    private final static QName INTEGRACAOFILENETCESERVICE_QNAME = new QName("http://facade.filenet.bradesco.com.br", "IntegracaoFileNetCEService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/LSCT/Desktop/GCC_gccn_integracaofilenet_ce_ws.ear/gccn_integracaofilenet_ce_ws.war/WEB-INF/wsdl/IntegracaoFileNetCE.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INTEGRACAOFILENETCESERVICE_WSDL_LOCATION = url;
        INTEGRACAOFILENETCESERVICE_EXCEPTION = e;
    }

    public IntegracaoFileNetCEService() {
        super(__getWsdlLocation(), INTEGRACAOFILENETCESERVICE_QNAME);
    }

    public IntegracaoFileNetCEService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INTEGRACAOFILENETCESERVICE_QNAME);
    }

    public IntegracaoFileNetCEService(URL wsdlLocation) {
        super(wsdlLocation, INTEGRACAOFILENETCESERVICE_QNAME);
    }

    public IntegracaoFileNetCEService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INTEGRACAOFILENETCESERVICE_QNAME);
    }

    public IntegracaoFileNetCEService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IntegracaoFileNetCEService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns IntegracaoFileNetCE
     */
    @WebEndpoint(name = "IntegracaoFileNetCE")
    public IntegracaoFileNetCE getIntegracaoFileNetCE() {
        return super.getPort(new QName("http://facade.filenet.bradesco.com.br", "IntegracaoFileNetCE"), IntegracaoFileNetCE.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IntegracaoFileNetCE
     */
    @WebEndpoint(name = "IntegracaoFileNetCE")
    public IntegracaoFileNetCE getIntegracaoFileNetCE(WebServiceFeature... features) {
        return super.getPort(new QName("http://facade.filenet.bradesco.com.br", "IntegracaoFileNetCE"), IntegracaoFileNetCE.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INTEGRACAOFILENETCESERVICE_EXCEPTION!= null) {
            throw INTEGRACAOFILENETCESERVICE_EXCEPTION;
        }
        return INTEGRACAOFILENETCESERVICE_WSDL_LOCATION;
    }

}
