
package br.com.bradesco.filenet.facade;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IntegracaoFileNetCEImagem", targetNamespace = "http://facade.filenet.bradesco.com.br")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IntegracaoFileNetCEImagem {


    /**
     * 
     * @param id
     * @param icor
     * @param negocio
     * @param password
     * @param user
     * @param propriedades
     */
    @WebMethod(action = "alterarClasseIcorPermissao")
    @RequestWrapper(localName = "alterarClasseIcorPermissao", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.AlterarClasseIcorPermissao")
    @ResponseWrapper(localName = "alterarClasseIcorPermissaoResponse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.AlterarClasseIcorPermissaoResponse")
    public void alterarClasseIcorPermissao(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "negocio", targetNamespace = "")
        String negocio,
        @WebParam(name = "icor", targetNamespace = "")
        String icor,
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "propriedades", targetNamespace = "")
        ArrayOfXsdNillableString propriedades);

    /**
     * 
     * @param negocio
     * @param idDocumento
     * @param password
     * @param user
     * @return
     *     returns br.com.bradesco.filenet.facade.ArrayOfXsdBase64Binary
     */
    @WebMethod(action = "obterConteudoDocumento")
    @WebResult(name = "obterConteudoDocumentoReturn", targetNamespace = "")
    @RequestWrapper(localName = "obterConteudoDocumento", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.ObterConteudoDocumento")
    @ResponseWrapper(localName = "obterConteudoDocumentoResponse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.ObterConteudoDocumentoResponse")
    public ArrayOfXsdBase64Binary obterConteudoDocumento(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "negocio", targetNamespace = "")
        String negocio,
        @WebParam(name = "idDocumento", targetNamespace = "")
        String idDocumento);

    /**
     * 
     * @param documentos
     * @param negocio
     * @param pathDestino
     * @param password
     * @param user
     * @param propriedades
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "criarDocumentoId")
    @WebResult(name = "criarDocumentoIdReturn", targetNamespace = "")
    @RequestWrapper(localName = "criarDocumentoId", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.CriarDocumentoId")
    @ResponseWrapper(localName = "criarDocumentoIdResponse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.CriarDocumentoIdResponse")
    public String criarDocumentoId(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "negocio", targetNamespace = "")
        String negocio,
        @WebParam(name = "pathDestino", targetNamespace = "")
        String pathDestino,
        @WebParam(name = "propriedades", targetNamespace = "")
        ArrayOfXsdNillableString propriedades,
        @WebParam(name = "documentos", targetNamespace = "")
        ArrayOfXsdBase64Binary documentos);

    /**
     * 
     * @param centroCustoPath
     * @param negocio
     * @param password
     * @param user
     * @param documentId
     */
    @WebMethod(action = "removerDocumentoCentroCusto")
    @RequestWrapper(localName = "removerDocumentoCentroCusto", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.RemoverDocumentoCentroCusto")
    @ResponseWrapper(localName = "removerDocumentoCentroCustoResponse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.RemoverDocumentoCentroCustoResponse")
    public void removerDocumentoCentroCusto(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "negocio", targetNamespace = "")
        String negocio,
        @WebParam(name = "centroCustoPath", targetNamespace = "")
        String centroCustoPath,
        @WebParam(name = "documentId", targetNamespace = "")
        String documentId);

    /**
     * 
     * @param choiceListName
     * @param negocio
     * @param choiceGroupName
     * @param password
     * @param user
     * @return
     *     returns br.com.bradesco.filenet.facade.ArrayOfArrayOfXsdNillableString
     */
    @WebMethod(action = "obterChoiceList")
    @WebResult(name = "obterChoiceListReturn", targetNamespace = "")
    @RequestWrapper(localName = "obterChoiceList", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.ObterChoiceList")
    @ResponseWrapper(localName = "obterChoiceListResponse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.ObterChoiceListResponse")
    public ArrayOfArrayOfXsdNillableString obterChoiceList(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "negocio", targetNamespace = "")
        String negocio,
        @WebParam(name = "choiceListName", targetNamespace = "")
        String choiceListName,
        @WebParam(name = "choiceGroupName", targetNamespace = "")
        String choiceGroupName);

    /**
     * 
     * @param id
     * @param classe
     * @param negocio
     * @param password
     * @param user
     * @param propriedades
     */
    @WebMethod(action = "alterarClasseNomePermissao")
    @RequestWrapper(localName = "alterarClasseNomePermissao", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.AlterarClasseNomePermissao")
    @ResponseWrapper(localName = "alterarClasseNomePermissaoResponse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.AlterarClasseNomePermissaoResponse")
    public void alterarClasseNomePermissao(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "negocio", targetNamespace = "")
        String negocio,
        @WebParam(name = "classe", targetNamespace = "")
        String classe,
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "propriedades", targetNamespace = "")
        ArrayOfXsdNillableString propriedades);

    /**
     * 
     * @param documentos
     * @param negocio
     * @param pathDestino
     * @param password
     * @param user
     * @param propriedades
     */
    @WebMethod(action = "criarDocumento")
    @RequestWrapper(localName = "criarDocumento", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.CriarDocumento")
    @ResponseWrapper(localName = "criarDocumentoResponse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.CriarDocumentoResponse")
    public void criarDocumento(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "negocio", targetNamespace = "")
        String negocio,
        @WebParam(name = "pathDestino", targetNamespace = "")
        String pathDestino,
        @WebParam(name = "propriedades", targetNamespace = "")
        ArrayOfXsdNillableString propriedades,
        @WebParam(name = "documentos", targetNamespace = "")
        ArrayOfXsdBase64Binary documentos);

    /**
     * 
     * @param whereProperties
     * @param negocio
     * @param searchTemplatePath
     * @param password
     * @param user
     * @param propertiesReturn
     * @return
     *     returns br.com.bradesco.filenet.facade.ArrayOfArrayOfXsdNillableString
     */
    @WebMethod(action = "consultarDocumentosSearchTemplate")
    @WebResult(name = "consultarDocumentosSearchTemplateReturn", targetNamespace = "")
    @RequestWrapper(localName = "consultarDocumentosSearchTemplate", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.ConsultarDocumentosSearchTemplate")
    @ResponseWrapper(localName = "consultarDocumentosSearchTemplateResponse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.ConsultarDocumentosSearchTemplateResponse")
    public ArrayOfArrayOfXsdNillableString consultarDocumentosSearchTemplate(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "negocio", targetNamespace = "")
        String negocio,
        @WebParam(name = "searchTemplatePath", targetNamespace = "")
        String searchTemplatePath,
        @WebParam(name = "whereProperties", targetNamespace = "")
        ArrayOfXsdNillableString whereProperties,
        @WebParam(name = "propertiesReturn", targetNamespace = "")
        ArrayOfXsdNillableString propertiesReturn);

    /**
     * 
     * @param id
     * @param icor
     * @param negocio
     * @param password
     * @param user
     * @param propriedades
     */
    @WebMethod(action = "alterarClasseIcor")
    @RequestWrapper(localName = "alterarClasseIcor", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.AlterarClasseIcor")
    @ResponseWrapper(localName = "alterarClasseIcorResponse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.AlterarClasseIcorResponse")
    public void alterarClasseIcor(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "negocio", targetNamespace = "")
        String negocio,
        @WebParam(name = "icor", targetNamespace = "")
        String icor,
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "propriedades", targetNamespace = "")
        ArrayOfXsdNillableString propriedades);

    /**
     * 
     * @param choiceItemName
     * @param choiceListName
     * @param negocio
     * @param choiceGroupName
     * @param password
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "obterValorItemChoiceList")
    @WebResult(name = "obterValorItemChoiceListReturn", targetNamespace = "")
    @RequestWrapper(localName = "obterValorItemChoiceList", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.ObterValorItemChoiceList")
    @ResponseWrapper(localName = "obterValorItemChoiceListResponse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.ObterValorItemChoiceListResponse")
    public String obterValorItemChoiceList(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "negocio", targetNamespace = "")
        String negocio,
        @WebParam(name = "choiceListName", targetNamespace = "")
        String choiceListName,
        @WebParam(name = "choiceGroupName", targetNamespace = "")
        String choiceGroupName,
        @WebParam(name = "choiceItemName", targetNamespace = "")
        String choiceItemName);

    /**
     * 
     * @param negocio
     * @param password
     * @param user
     * @param propertiesReturn
     * @param storedSearchPath
     * @return
     *     returns br.com.bradesco.filenet.facade.ArrayOfArrayOfXsdNillableString
     */
    @WebMethod(action = "consultarDocumentosStoredSearch")
    @WebResult(name = "consultarDocumentosStoredSearchReturn", targetNamespace = "")
    @RequestWrapper(localName = "consultarDocumentosStoredSearch", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.ConsultarDocumentosStoredSearch")
    @ResponseWrapper(localName = "consultarDocumentosStoredSearchResponse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.ConsultarDocumentosStoredSearchResponse")
    public ArrayOfArrayOfXsdNillableString consultarDocumentosStoredSearch(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "negocio", targetNamespace = "")
        String negocio,
        @WebParam(name = "storedSearchPath", targetNamespace = "")
        String storedSearchPath,
        @WebParam(name = "propertiesReturn", targetNamespace = "")
        ArrayOfXsdNillableString propertiesReturn);

    /**
     * 
     * @param id
     * @param classe
     * @param negocio
     * @param password
     * @param user
     * @param propriedades
     */
    @WebMethod(action = "alterarClasseNome")
    @RequestWrapper(localName = "alterarClasseNome", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.AlterarClasseNome")
    @ResponseWrapper(localName = "alterarClasseNomeResponse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.AlterarClasseNomeResponse")
    public void alterarClasseNome(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "negocio", targetNamespace = "")
        String negocio,
        @WebParam(name = "classe", targetNamespace = "")
        String classe,
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "propriedades", targetNamespace = "")
        ArrayOfXsdNillableString propriedades);

    /**
     * 
     * @param negocio
     * @param folderPath
     * @param password
     * @param user
     * @param documentId
     */
    @WebMethod(action = "removerDocumentoFolder")
    @RequestWrapper(localName = "removerDocumentoFolder", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.RemoverDocumentoFolder")
    @ResponseWrapper(localName = "removerDocumentoFolderResponse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.RemoverDocumentoFolderResponse")
    public void removerDocumentoFolder(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "negocio", targetNamespace = "")
        String negocio,
        @WebParam(name = "folderPath", targetNamespace = "")
        String folderPath,
        @WebParam(name = "documentId", targetNamespace = "")
        String documentId);

    /**
     * 
     * @param negocio
     * @param folderPath
     * @param password
     * @param user
     * @param documentId
     */
    @WebMethod(action = "adicionarDocumentoFolder")
    @RequestWrapper(localName = "adicionarDocumentoFolder", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.AdicionarDocumentoFolder")
    @ResponseWrapper(localName = "adicionarDocumentoFolderResponse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.AdicionarDocumentoFolderResponse")
    public void adicionarDocumentoFolder(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "negocio", targetNamespace = "")
        String negocio,
        @WebParam(name = "folderPath", targetNamespace = "")
        String folderPath,
        @WebParam(name = "documentId", targetNamespace = "")
        String documentId);

}
