
package br.com.bradesco.filenet.facade;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IntegracaoFileNetCE", targetNamespace = "http://facade.filenet.bradesco.com.br")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IntegracaoFileNetCE {


    /**
     * 
     * @param path
     * @param negocio
     * @param password
     * @param user
     */
    @WebMethod(action = "excluirDocumentoPorPath")
    @RequestWrapper(localName = "excluirDocumentoPorPath", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.ExcluirDocumentoPorPath")
    @ResponseWrapper(localName = "excluirDocumentoPorPathResponse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.ExcluirDocumentoPorPathResponse")
    public void excluirDocumentoPorPath(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "negocio", targetNamespace = "")
        String negocio,
        @WebParam(name = "path", targetNamespace = "")
        String path);

    /**
     * 
     * @param idPasta
     * @param negocio
     * @param password
     * @param user
     * @param propriedades
     */
    @WebMethod(action = "atualizaPropriedadesPasta")
    @RequestWrapper(localName = "atualizaPropriedadesPasta", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.AtualizaPropriedadesPasta")
    @ResponseWrapper(localName = "atualizaPropriedadesPastaResponse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.AtualizaPropriedadesPastaResponse")
    public void atualizaPropriedadesPasta(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "negocio", targetNamespace = "")
        String negocio,
        @WebParam(name = "idPasta", targetNamespace = "")
        String idPasta,
        @WebParam(name = "propriedades", targetNamespace = "")
        ArrayOfXsdNillableString propriedades);

    /**
     * 
     * @param negocio
     * @param idDocumento
     * @param password
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "downloadDocumento")
    @WebResult(name = "downloadDocumentoReturn", targetNamespace = "")
    @RequestWrapper(localName = "downloadDocumento", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.DownloadDocumento")
    @ResponseWrapper(localName = "downloadDocumentoResponse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.DownloadDocumentoResponse")
    public String downloadDocumento(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "negocio", targetNamespace = "")
        String negocio,
        @WebParam(name = "idDocumento", targetNamespace = "")
        String idDocumento);

    /**
     * 
     * @param pathOrigem
     * @param negocio
     * @param pathDestino
     * @param pasta
     * @param password
     * @param user
     */
    @WebMethod(action = "moverPasta")
    @RequestWrapper(localName = "moverPasta", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.MoverPasta")
    @ResponseWrapper(localName = "moverPastaResponse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.MoverPastaResponse")
    public void moverPasta(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "negocio", targetNamespace = "")
        String negocio,
        @WebParam(name = "pasta", targetNamespace = "")
        String pasta,
        @WebParam(name = "pathOrigem", targetNamespace = "")
        String pathOrigem,
        @WebParam(name = "pathDestino", targetNamespace = "")
        String pathDestino);

    /**
     * 
     * @param path
     * @param negocio
     * @param password
     * @param user
     * @param propertiesReturn
     * @return
     *     returns br.com.bradesco.filenet.facade.ArrayOfArrayOfXsdNillableString
     */
    @WebMethod(action = "pesquisarDocumentosPorPath")
    @WebResult(name = "pesquisarDocumentosPorPathReturn", targetNamespace = "")
    @RequestWrapper(localName = "pesquisarDocumentosPorPath", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.PesquisarDocumentosPorPath")
    @ResponseWrapper(localName = "pesquisarDocumentosPorPathResponse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.PesquisarDocumentosPorPathResponse")
    public ArrayOfArrayOfXsdNillableString pesquisarDocumentosPorPath(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "negocio", targetNamespace = "")
        String negocio,
        @WebParam(name = "path", targetNamespace = "")
        String path,
        @WebParam(name = "propertiesReturn", targetNamespace = "")
        ArrayOfXsdNillableString propertiesReturn);

    /**
     * 
     * @param qtdeMaxReg
     * @param sql
     * @param negocio
     * @param password
     * @param user
     * @return
     *     returns br.com.bradesco.filenet.facade.ArrayOfArrayOfXsdNillableString
     */
    @WebMethod(action = "pesquisarDocumentosPorQuery")
    @WebResult(name = "pesquisarDocumentosPorQueryReturn", targetNamespace = "")
    @RequestWrapper(localName = "pesquisarDocumentosPorQuery", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.PesquisarDocumentosPorQuery")
    @ResponseWrapper(localName = "pesquisarDocumentosPorQueryResponse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.PesquisarDocumentosPorQueryResponse")
    public ArrayOfArrayOfXsdNillableString pesquisarDocumentosPorQuery(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "negocio", targetNamespace = "")
        String negocio,
        @WebParam(name = "sql", targetNamespace = "")
        ArrayOfXsdNillableString sql,
        @WebParam(name = "qtdeMaxReg", targetNamespace = "")
        int qtdeMaxReg);

    /**
     * 
     * @param qtdeMaxReg
     * @param select
     * @param negocio
     * @param from
     * @param where
     * @param password
     * @param user
     * @return
     *     returns br.com.bradesco.filenet.facade.ArrayOfArrayOfXsdNillableString
     */
    @WebMethod(action = "pesquisarDocumentosPorQueryWhere")
    @WebResult(name = "pesquisarDocumentosPorQueryWhereReturn", targetNamespace = "")
    @RequestWrapper(localName = "pesquisarDocumentosPorQueryWhere", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.PesquisarDocumentosPorQueryWhere")
    @ResponseWrapper(localName = "pesquisarDocumentosPorQueryWhereResponse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.PesquisarDocumentosPorQueryWhereResponse")
    public ArrayOfArrayOfXsdNillableString pesquisarDocumentosPorQueryWhere(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "negocio", targetNamespace = "")
        String negocio,
        @WebParam(name = "select", targetNamespace = "")
        String select,
        @WebParam(name = "from", targetNamespace = "")
        String from,
        @WebParam(name = "where", targetNamespace = "")
        String where,
        @WebParam(name = "qtdeMaxReg", targetNamespace = "")
        int qtdeMaxReg);

    /**
     * 
     * @param id
     * @param negocio
     * @param password
     * @param user
     */
    @WebMethod(action = "excluirDocumentoPorId")
    @RequestWrapper(localName = "excluirDocumentoPorId", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.ExcluirDocumentoPorId")
    @ResponseWrapper(localName = "excluirDocumentoPorIdResponse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.ExcluirDocumentoPorIdResponse")
    public void excluirDocumentoPorId(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "negocio", targetNamespace = "")
        String negocio,
        @WebParam(name = "id", targetNamespace = "")
        String id);

    /**
     * 
     * @param path
     * @param negocio
     * @param pasta
     * @param password
     * @param user
     */
    @WebMethod(action = "excluirPasta")
    @RequestWrapper(localName = "excluirPasta", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.ExcluirPasta")
    @ResponseWrapper(localName = "excluirPastaResponse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.ExcluirPastaResponse")
    public void excluirPasta(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "negocio", targetNamespace = "")
        String negocio,
        @WebParam(name = "pasta", targetNamespace = "")
        String pasta,
        @WebParam(name = "path", targetNamespace = "")
        String path);

    /**
     * 
     * @param path
     * @param negocio
     * @param className
     * @param pasta
     * @param password
     * @param user
     * @param propriedades
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "criarPastaComClasse")
    @WebResult(name = "criarPastaComClasseReturn", targetNamespace = "")
    @RequestWrapper(localName = "criarPastaComClasse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.CriarPastaComClasse")
    @ResponseWrapper(localName = "criarPastaComClasseResponse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.CriarPastaComClasseResponse")
    public String criarPastaComClasse(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "negocio", targetNamespace = "")
        String negocio,
        @WebParam(name = "pasta", targetNamespace = "")
        String pasta,
        @WebParam(name = "path", targetNamespace = "")
        String path,
        @WebParam(name = "className", targetNamespace = "")
        String className,
        @WebParam(name = "propriedades", targetNamespace = "")
        ArrayOfXsdNillableString propriedades);

    /**
     * 
     * @param negocio
     * @param idDocumento
     * @param password
     * @param user
     * @param propriedades
     */
    @WebMethod(action = "atualizaPropriedadesDocumento")
    @RequestWrapper(localName = "atualizaPropriedadesDocumento", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.AtualizaPropriedadesDocumento")
    @ResponseWrapper(localName = "atualizaPropriedadesDocumentoResponse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.AtualizaPropriedadesDocumentoResponse")
    public void atualizaPropriedadesDocumento(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "negocio", targetNamespace = "")
        String negocio,
        @WebParam(name = "idDocumento", targetNamespace = "")
        String idDocumento,
        @WebParam(name = "propriedades", targetNamespace = "")
        ArrayOfXsdNillableString propriedades);

    /**
     * 
     * @param path
     * @param negocio
     * @param pasta
     * @param password
     * @param user
     */
    @WebMethod(action = "criarPasta")
    @RequestWrapper(localName = "criarPasta", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.CriarPasta")
    @ResponseWrapper(localName = "criarPastaResponse", targetNamespace = "http://facade.filenet.bradesco.com.br", className = "br.com.bradesco.filenet.facade.CriarPastaResponse")
    public void criarPasta(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "negocio", targetNamespace = "")
        String negocio,
        @WebParam(name = "pasta", targetNamespace = "")
        String pasta,
        @WebParam(name = "path", targetNamespace = "")
        String path);

}
