
package br.com.bradesco.filenet.facade;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IntegracaoFileNetCEImagemService", targetNamespace = "http://facade.filenet.bradesco.com.br", wsdlLocation = "file:/C:/Users/LSCT/Desktop/GCC_gccn_integracaofilenet_ce_ws.ear/gccn_integracaofilenet_ce_ws.war/WEB-INF/wsdl/IntegracaoFileNetCEImagem.wsdl")
public class IntegracaoFileNetCEImagemService
    extends Service
{

    private final static URL INTEGRACAOFILENETCEIMAGEMSERVICE_WSDL_LOCATION;
    private final static WebServiceException INTEGRACAOFILENETCEIMAGEMSERVICE_EXCEPTION;
    private final static QName INTEGRACAOFILENETCEIMAGEMSERVICE_QNAME = new QName("http://facade.filenet.bradesco.com.br", "IntegracaoFileNetCEImagemService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/LSCT/Desktop/GCC_gccn_integracaofilenet_ce_ws.ear/gccn_integracaofilenet_ce_ws.war/WEB-INF/wsdl/IntegracaoFileNetCEImagem.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INTEGRACAOFILENETCEIMAGEMSERVICE_WSDL_LOCATION = url;
        INTEGRACAOFILENETCEIMAGEMSERVICE_EXCEPTION = e;
    }

    public IntegracaoFileNetCEImagemService() {
        super(__getWsdlLocation(), INTEGRACAOFILENETCEIMAGEMSERVICE_QNAME);
    }

    public IntegracaoFileNetCEImagemService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INTEGRACAOFILENETCEIMAGEMSERVICE_QNAME);
    }

    public IntegracaoFileNetCEImagemService(URL wsdlLocation) {
        super(wsdlLocation, INTEGRACAOFILENETCEIMAGEMSERVICE_QNAME);
    }

    public IntegracaoFileNetCEImagemService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INTEGRACAOFILENETCEIMAGEMSERVICE_QNAME);
    }

    public IntegracaoFileNetCEImagemService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IntegracaoFileNetCEImagemService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns IntegracaoFileNetCEImagem
     */
    @WebEndpoint(name = "IntegracaoFileNetCEImagem")
    public IntegracaoFileNetCEImagem getIntegracaoFileNetCEImagem() {
        return super.getPort(new QName("http://facade.filenet.bradesco.com.br", "IntegracaoFileNetCEImagem"), IntegracaoFileNetCEImagem.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IntegracaoFileNetCEImagem
     */
    @WebEndpoint(name = "IntegracaoFileNetCEImagem")
    public IntegracaoFileNetCEImagem getIntegracaoFileNetCEImagem(WebServiceFeature... features) {
        return super.getPort(new QName("http://facade.filenet.bradesco.com.br", "IntegracaoFileNetCEImagem"), IntegracaoFileNetCEImagem.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INTEGRACAOFILENETCEIMAGEMSERVICE_EXCEPTION!= null) {
            throw INTEGRACAOFILENETCEIMAGEMSERVICE_EXCEPTION;
        }
        return INTEGRACAOFILENETCEIMAGEMSERVICE_WSDL_LOCATION;
    }

}
